### ISSUE TITLE
Префикс добавляется дважды

### ISSUE THREAD

**Issue by sombro** [vezetvsem/react-classname-prefix-loader#1]
В такой ситуации:

```
render() {
        const asd = classnames(
            'ditle',
            'ditle--' + this.props.status,
        );

        return (
            <div className={asd}>{this.props.text}</div>
        );
    }
```

Получаем

`<div class="rg-ditle rg-rg-ditle--active">...</div>`

Предположительно, скрипт срабатывает дважды на классы внутри `classnames` с постфиксом `--`, если у них нет никаких префиксов (например, с классом `ditle__asd--` сработает верно).

**Comment by antonsivogrivov** [comment]
fixed in 1.0.7
